# Generated by Django 3.2.15 on 2023-02-16 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_coordinates', '0003_auto_20230215_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90, 'Широта не может быть меньше -90'), django.core.validators.MaxValueValidator(90, 'Широта не может быть больше 90')], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lng',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90, 'Долгота не может быть меньше -90'), django.core.validators.MaxValueValidator(90, 'Долгота не может быть больше 90')], verbose_name='Долгота'),
        ),
    ]
