# Generated by Django 3.2.15 on 2023-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_coordinates', '0006_rename_coordinate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
