#!/bin/bash
set -e

cd /opt/BurgerKing
echo "Progress 1 of 8 -- go to the /opt/BurgerKing directory"

git pull
echo "Progress 2 of 8 -- update repository"

. ./venv/bin/activate
echo "Progress 3 of 8 -- activate env"

pip install -r requirements.txt
echo "Progress 4 of 8 -- install all requirements"

python manage.py migrate --noinput
echo "Progress 5 of 8 -- migrate bd"

source ~/.bashrc
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
echo "Progress 6 of 8 - Preassembler frontend"

python3 manage.py collectstatic --noinput
echo "Progress 7 of 8 -- collectstatic"

sudo systemctl restart burger_gunicorn.service
sudo systemctl reload nginx.service
echo "Progress 8 of 8 -- restart gunicorn and nginx servicies"

source ./.env
CURRENT_COMMIT=$(git rev-parse --verify HEAD)
COMMENT=$(git log -1 --format=%s)
DATE=$(date)
USER=$(git config remote.origin.url)
curl -H "X-Rollbar-Access-Token: $ROLLBAR_TOKEN" -H "Content-Type:
application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{
    "environment": "production",
    "revision": "${CURRENT_COMMIT}",
    "rollbar_name": "john",
    "local_username":  "circle-ci",
    "comment": "Tuesday deployment",
    "status": "succeeded"
 }'

echo "Congratulations, the deployment was successful"



