#!/bin/bash
set -e

sudo docker-compose up --build -d

source ./.env
CURRENT_COMMIT=$(git rev-parse --verify HEAD)
COMMENT=$(git log -1 --format=%s)
DATE=$(date)
USER=$(git config remote.origin.url)
curl -H "X-Rollbar-Access-Token: $ROLLBAR_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{"environment": "'"$ROLLBAR_ENVIRONMENT"'", "revision": "'"$CURRENT_COMMIT"'", "rollbar_name": "'"$USER $DATE"'", "local_username": "'"$USER"'", "comment": "'"$COMMENT"'", "status": "succeeded"}'

echo "Congratulations, the deployment was successful"
