version: "3.9"

services:
  burger_postgres:
    image: postgres:15
    container_name: burger_postgres
    volumes:
      - postgres:/var/postgresql/data
    env_file:
      - .env
    restart: always
  burger_project:
    build: .
    tty: true
    container_name: burger_project
    depends_on:
      - burger_postgres
    volumes:
      - static_volume:/opt/starburger/static
      - media_volume:/opt/starburger/media
    env_file:
      - .env
    ports:
      - 8000:8000
    command: >
      bash -c "python3 manage.py collectstatic --noinput && \
      python3 manage.py migrate --noinput && \
      gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    restart: always
  nginx:
    image: nginx:alpine
    depends_on:
      - burger_project
    links:
      - burger_project
    volumes:
      - ./data/nginx/dev:/etc/nginx/conf.d
      - static_volume:/opt/starburger/static
      - media_volume:/opt/starburger/media
    ports:
      - 1337:80
    restart: always


volumes:
  static_volume:
  media_volume:
  postgres:
