# Generated by Django 3.0.7 on 2020-06-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_auto_20200619_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
