# Generated by Django 3.0.7 on 2020-06-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_auto_20200619_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPosition',
            new_name='OrderItem',
        ),
    ]
