# Generated by Django 3.0.7 on 2020-06-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0009_auto_20200619_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
