# Generated by Django 3.0.7 on 2020-06-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0014_auto_20200619_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrated_restaurants', to='foodcartapp.Customer', verbose_name='администратор'),
        ),
    ]
