# Generated by Django 3.0.7 on 2020-06-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0018_remove_restaurant_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='new_admin',
            new_name='admin',
        ),
    ]
