# Generated by Django 3.0.7 on 2020-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0021_auto_20200619_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(1, 'наличными после доставки')], db_index=True, default=1, verbose_name='тип заказа'),
        ),
    ]
