# Generated by Django 3.0.7 on 2020-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0022_auto_20200619_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
