# Generated by Django 2.2.5 on 2020-09-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0032_remove_restaurant_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingridients',
            new_name='description',
        ),
    ]
