# Generated by Django 3.0.7 on 2021-01-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0035_auto_20200928_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodcartapp.Product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
