# Generated by Django 3.2.15 on 2023-01-28 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230128_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Колличество'),
        ),
    ]
