# Generated by Django 3.2.15 on 2023-02-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CS', 'Наличностью'), ('CD', 'Электронно'), ('NO', 'Невыбрано')], db_index=True, default='RA', max_length=2, verbose_name='Оплата'),
        ),
    ]
