# Generated by Django 3.2.15 on 2023-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='foodcartapp.Restaurant', verbose_name='заказ'),
        ),
    ]
