# Generated by Django 3.2.15 on 2023-02-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(blank=True, related_name='orders', to='foodcartapp.Restaurant', verbose_name='Ресторан для приготовления'),
        ),
    ]
