# Generated by Django 3.2.15 on 2023-03-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_rename_restaurant_order_cooking_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cooking_restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан для приготовления'),
        ),
    ]
