# Generated by Django 3.2.15 on 2023-03-06 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Необработанный'), ('PR', 'Принят в работу'), ('CO', 'Приготовление'), ('DL', 'Доставка'), ('CL', 'Выполнен')], db_index=True, default='RE', max_length=2, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть меньше 0')], verbose_name='Стоимость'),
        ),
    ]
