# Generated by Django 3.2.15 on 2023-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
