# Generated by Django 3.2.15 on 2023-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_coordinates', '0004_auto_20230216_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
