# Generated by Django 3.0.7 on 2020-06-19 09:19

from django.db import migrations


def fill_city_field(apps, schema_editor):
    Hotel = apps.get_model("foodcartapp", "Hotel")
    for hotel in Hotel.objects.all():
        hotel.city = hotel.location.city
        hotel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_hotel_city'),
    ]

    operations = [
        migrations.RunPython(fill_city_field),
    ]
