# Generated by Django 3.0.7 on 2020-06-19 09:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('foodcartapp', '0012_auto_20200619_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Restaurant',
        ),
    ]
