# Generated by Django 3.0.7 on 2020-06-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0017_auto_20200619_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
