# Generated by Django 3.0.7 on 2020-06-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0024_product_ingridients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
