# Generated by Django 3.0.7 on 2020-06-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0027_auto_20200629_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='restaurant',
        ),
    ]
