# Generated by Django 3.2.15 on 2023-02-05 14:28

from django.db import migrations


def calculate_price_to_all_order_item(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.filter(price=0)
    for order_item in order_items.iterator():
        order_item.price = order_item.quantity * order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230205_1305'),
    ]

    operations = [
        migrations.RunPython(calculate_price_to_all_order_item),
    ]
