# Generated by Django 3.2.15 on 2023-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230205_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RA', 'Необработанный'), ('HR', 'Принят в работу'), ('AS', 'Сборка'), ('DL', 'Доставка'), ('EN', 'Выполнен')], default='RA', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
