# Generated by Django 3.2.15 on 2023-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='Коментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RA', 'Необработанный'), ('HR', 'Принят в работу'), ('AS', 'Сборка'), ('DL', 'Доставка'), ('EN', 'Выполнен')], db_index=True, default='RA', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
