# Generated by Django 3.2.15 on 2023-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(default=0, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='foodcartapp.Restaurant', verbose_name='Ресторан для приготовления'),
        ),
    ]
