# Generated by Django 3.2.15 on 2023-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230302_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Коментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CS', 'Наличностью'), ('CD', 'Электронно'), ('NO', 'Не выбрано')], db_index=True, default='NO', max_length=2, verbose_name='Оплата'),
        ),
    ]
